name: build

on: [ push ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x 

    - name: Build
      run: dotnet publish -c Release

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: WpfKenBurns
        path: WpfKenBurns/bin/Release/net5-windows/win-x64/publish/Ken Burns.scr